services:
  app:
    container_name: swoole1_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/var/www
      - /var/www/vendor
    depends_on:
      - mysql
    networks:
      - laravel
    # command: php artisan serve --host=0.0.0.0 --port=8000
    command: php artisan octane:start --host=0.0.0.0 --port=9000

  mysql:
    image: mysql:8.0
    container_name: swoole1_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  node:
    image: node:22-alpine
    container_name: swoole1_node
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"  # Vite dev server port
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge